name: Deploy to App Engine

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_KEY_APP_ENGINE.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      run: |
        echo '${{ secrets.GOOGLE_CLOUD_KEY_APP_ENGINE }}' | base64 --decode > service_account.json
        echo "Installing Google Cloud SDK..."
        CLOUDSDK_CORE_DISABLE_PROMPTS=1 curl https://sdk.cloud.google.com | bash
        source $HOME/google-cloud-sdk/path.bash.inc
        gcloud auth activate-service-account --key-file=service_account.json


    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GOOGLE_CLOUD_KEY_APP_ENGINE.PROJECT_ID }}/my-image .

    - name: Push Docker Image
      run: |
        docker push gcr.io/${{ secrets.GOOGLE_CLOUD_KEY_APP_ENGINE.PROJECT_ID }}/my-image

    - name: Deploy to App Engine
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GCLOUD_SA_KEY }}
        gcloud --quiet config set project $PROJECT_ID
        gcloud app deploy