name: Deploy to App Engine

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_KEY_APP_ENGINE.project_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY_APP_ENGINE }}

    - name: Build Docker Image
      run: |
        docker build -t "gcr.io/$project_id/my-image" .

    - name: Push Docker Image
      run: |
        docker push gcr.io/$PROJECT_ID/my-image

    - name: Deploy to App Engine
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GOOGLE_CLOUD_KEY_APP_ENGINE }}
        gcloud --quiet config set project $PROJECT_ID
        gcloud app deploy